name: Flutter Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image:  cirrusci/flutter:v1.10.7
      volumes:
        - ${PWD}/app
      options: --workdir /app

    steps:
      - uses: actions/checkout@v1
      - name: Run tests
        run: flutter test
